version: '3.3'
services:
  webapp:
    image: trim0917/webapp:latest
    volumes:
      - type: bind
        source: ./log
        target: /App/WebApp/log
      - type: bind
        source: ./archive
        target: /App/WebApp/archive
    ports:
      - "9100:9100"
    restart: always